### ISSUE TITLE
'this.props' undefined in received method

### ISSUE THREAD

**Issue by zohaibahmeds63** [cpunion/react-native-actioncable#1]
Hello there,

I am using Redux for state management. I intend to call an action after the data is received via action cable, but I am unable to access `this.props` in the received callback method, as given in the example.

Any guidance would be extremely appreciated.

**Comment by cpunion** [comment]
Can you try this code? modified from README.md.

```javascript
componentDidMount () {
        this.subscription = this.context.cable.subscriptions.create(
            'ChatChannel',
            {
                received (data) {
                    this.props.dispatch(xxxAction())
                }
            }
        )
    }
```

**Comment by tauqeer-ahmad** [comment]
I have tried with the following code but still props are undefined.

`componentDidMount () {
    this.subscription = this.context.cable.subscriptions.create(
        'SessionChannel',
        {
          received (data) {
            console.log(data)
             this.props.fetchSession(this.props.route.session_id);
          }
        }
    )
  }
`

Any ideas about this issue?

**Comment by cpunion** [comment]
Maybe I forgot some rules.

In the object:
```
            {
                received (data) {
                    this.props.dispatch(xxxAction())
                }
            }
```

`this` is point to this object, isn't the component. You can save `this` first.

E.g.:
```
componentDidMount () {
        const self = this // <----- Save this to self
        this.subscription = this.context.cable.subscriptions.create(
            'ChatChannel',
            {
                received (data) {
                    self.props.dispatch(xxxAction())  // <---------- Use self instead of this
                }
            }
        )
    }
```

**Comment by tauqeer-ahmad** [comment]
Thanks @cpunion it is working now 👍

**Comment by cpunion** [comment]
Thanks for feedback.

@zohaibahmeds63 Did you solve the problem?

**Comment by zohaibahmeds63** [comment]
Yes, Thanks a lot for providing help!
