### ISSUE TITLE
iOS background functionality

### ISSUE THREAD

**Issue by EsdrasEtrenne** [cpunion/react-native-actioncable#10]
Hi, is there any way to continue getting broadcasts when the app is in the background for iOS? Works for android but not iOS

**Comment by cpunion** [comment]
As I known that processing network in background is not a good way, maybe the app be killed, push notification is better.

https://stackoverflow.com/questions/40339747/react-native-web-socket-in-background-mode you can try this way if necessary.

**Comment by EsdrasEtrenne** [comment]
Awesome thanks I just wanted to know.
