### ISSUE TITLE
Using `const cable = RNActionCable.createConsuemr()` somewhere else

### ISSUE THREAD

**Issue by masudhossain** [cpunion/react-native-actioncable#11]
To make a user connect to a /cable server, we have to put put in their token after the /cable, or else the server won't know which specific user is trying to connect to to the actioncable /cable server. 

Reference: https://scontent-mia3-2.xx.fbcdn.net/v/t31.0-8/22829689_10155779623927071_5346083355880301983_o.jpg?oh=e5364c297087412241f388e3134ef569&oe=5A62D978

And I'm unable to grab the params.token or any async storage tokens, and place it into that const cable. 

Is there a workaround for this?

**Comment by cpunion** [comment]
I had tested two ways:

1. Your api server domain is same as you web server’s, just process in your Channel.

2. Mount ActionCable server to /cable/:token and process in channel.

Sorry for no details, I’m on a meet up.
