### ISSUE TITLE
IOS : use of @ symbol for calling server side methods gives syntax error

### ISSUE THREAD

**Issue by sainath13** [cpunion/react-native-actioncable#2]
`componentDidMount () {
        this.subscription = cable.subscriptions.create(
            'ChatChannel',
            {
                speak(message){
                    console.log("Message")
                    **@perform 'speak', message : message**
                }
            }
        )
    }`

**Comment by cpunion** [comment]
@sainath13 You are using Coffee Script syntax, it should be converted to JavaScript syntax.

**Comment by sainath13** [comment]
Oh. Thanks. worked.
