### ISSUE TITLE
How do I send JWT when creating a new connection for authentication?

### ISSUE THREAD

**Issue by zekedran** [cpunion/react-native-actioncable#4]

**Comment by cpunion** [comment]
**The easy way:**

Send authentication in `connected` event handler, it must be the first request on connection.

**The hacking way:**

I guess you can hack `ActionCable.Consumer.constructor`, `ActionCable.Connection.contrusctor` and `ActionCable.Connection.open` to add header options, and use it in WebSocket.

**Comment by zekedran** [comment]
I looked at your cookie library _(which you mentioned as depricated)_, and I did it the similar way, append my **JWT** to websocket protocols and parse it in the server.

[And today I updated the packages and found that rn-action-cable uses funcs from actioncable react :\ ]

> The easy way:
> 
> Send authentication in connected event handler, it must be the first request on connection.
> 
> The hacking way:
> 
> I guess you can hack ActionCable.Consumer.constructor, ActionCable.Connection.contrusctor and ActionCable.Connection.open to add header options, and use it in WebSocket.

For the connection to get successfully established on my `RoR` server, I need to send jwt before getting connected i.e, in the request for websocket connection

And I didn't get the second one, did you mean _something like adding to existing headers like protocols?_

**Comment by cpunion** [comment]
> I looked at your cookie library (which you mentioned as depricated), and I did it the similar way, append my JWT to websocket protocols and parse it in the server.

Did it work?

> And I didn't get the second one, did you mean something like adding to existing headers like protocols?

Yes, but I didn't test. And maybe has another way, put the JWT into query params of actioncable's url.  Like this: '/cable?jwt=MY_JWT'. I found an example at http://stackoverflow.com/questions/35501931/send-auth-token-for-authentification-to-actioncable, see the first reply.

**Comment by zekedran** [comment]
> Did it work?

Yes, it did, and I created a [handy lib](https://github.com/zekedran/action-cable-react-jwt) just like your cookie lib, and published the same on npm so I can use it just like other libs in my projects...

And reg `/cable?token=1234`, it could be vulnerable as it may end up in logs and system process information available to others that have access to the server -> more [here](http://stackoverflow.com/a/32725284/3125070)

So ideally, it's better to encrypt the token when used in urls

**Comment by cpunion** [comment]
Thanks for your sharing.

**Comment by vitalyliber** [comment]
I have used "react-native-cookie" for setting cookies with token before connect. It works fine.

**Comment by zedtux** [comment]
I have exactly the same use case here, a React Native app, using a JWT to authenticate with the API from my Rails app, and now I'm implementing ActionCable in order to get the realtime updates.

Like @zekedran I don't like to send the JWT in the WS URL so I followed the way he did it, passing the JWT in the `protocols` of the WebSocket and parsing the `request.headers[:HTTP_SEC_WEBSOCKET_PROTOCOL]` on the Rails side in order to retrieve the JWT.

That being said, I'm not using @zekedran's library as it seems to have copy of the `actioncable` while this library perfectly uses the official library.
Instead, what I did is to update the `ActionCable.INTERNAL.protocols` before to call the `ActionCable.createConsumer()` :

```javascript
  // ...
  setupAndConnect() {
    ActionCable.INTERNAL.protocols.push(this.props.jwt)
    const cable = ActionCable.createConsumer(this.props.websocketUrl)
    cable.subscriptions.create(channelName, {
      // ...
    }
  }
  //..
```

Which does exactly the same as @zekedran's library.

**Comment by maharjanaman** [comment]
@zedtux can you provide proper example for this?? Also when I just import ActionCable from this library gives me error `TypeError: Cannot read property 'split' of undefined`. Is this library outdated???

**Comment by zedtux** [comment]
@maharjanaman of course this library is outdated ! As I stated in my comment, a copy of the original library has been imported. Since, newer versions was released, but no updated in this lib. That's the reason why I'm not using it.

What part are you missing that I should share here?

**Comment by zedtux** [comment]
`ActionCable` is the library, which as [the `INTERNAL` constant](https://github.com/rails/rails/blob/master/actioncable/app/assets/javascripts/action_cable.coffee.erb#L6).

> ... unable to get the result.

What does that mean ?
