### ISSUE TITLE
Not working with iOS

### ISSUE THREAD

**Issue by hazemhagrass** [cpunion/react-native-actioncable#7]
Hi,
It's not working at all on iOS, however it's working on android with no issues, are you sure it's smooth and funcional on iOS?

**Comment by hazemhagrass** [comment]
Any updates!!

**Comment by cpunion** [comment]
Sorry so late for response.

I just tried in react-native@0.44 on iOS, it works fine.

How is your code? And what error messages are outputted?

**Comment by cpunion** [comment]
See a workable example at https://github.com/cpunion/react-native-actioncable/issues/8
