### ISSUE TITLE
Example?

### ISSUE THREAD

**Issue by masudhossain** [cpunion/react-native-actioncable#8]
Is there any possibility you could upload an example of a working react native app?

**Comment by cpunion** [comment]
See https://github.com/cpunion/TestRNActionCable

Test steps:

1. Open ios project, run it in iOS Simulator.

2. In the `server` folder, run `bundle exec rails s`.

3. Open http://localhost:3000/message in browser, input some test and
click 'Send message'

4. You will see the messages displayed in iOS Simulator.
